add handle GetOSById
s21platform/gateway-service pull request #17
Opened 2024-11-17 22:30 UTC by Snegov1k

2024-11-17 23:35 UTC, Snegov1k commented
пока не мерджим, тк после рефакторинга optionhub наебнется

2024-11-18 18:36 UTC, alexseipopov requested changes

2024-11-18 18:36 UTC, alexseipopov commented on internal/useCase/option/option.go
> +	id, err := extractOSID(r)
Тут не совсем так. 
1) Мы хотим получать все ОС из опшнхаба. Там под это есть другой метод с пагинацией. Это не тот метод grpc.
2) В методе GET не используют Body!!! Это технически возможно но семантически не верно. В GET используют только Path и Query параметры

2024-11-18 18:36 UTC, alexseipopov commented on internal/useCase/option/option.go
> +func extractOSID(r *http.Request) (int64, error) {
Соответсвенно extract воообще не нужен

2024-11-19 14:19 UTC, Snegov1k commented on internal/useCase/option/option.go
> +	id, err := extractOSID(r)
Ручка под все ОС не имплементирована, сейчас из готовых есть только:
GetOsById
AddOs
GetOsBySearchName

2024-11-19 14:19 UTC, Snegov1k commented on internal/useCase/option/option.go
> +	id, err := extractOSID(r)
get запрос сейчас подправлю

2024-11-29 17:38 UTC, alexseipopov requested changes

2024-11-29 17:38 UTC, alexseipopov commented on internal/useCase/option/option.go
> +	if name == "" {
вот жто условие нужно удалить. Если нейм не придет - пусть уходит пустая строка

2024-11-29 20:22 UTC, alexseipopov approved these changes

2024-11-29 20:25 UTC, merged